config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'teams#index'

  resources :teams do

    member do
      post :join
      post :quit
    end

    resources :events, only: [:index]

    resources :projects do
      member do
        post :join
        post :quit
      end
    end

  end

  resources :projects do
    resources :todos, only: [:new, :create, :edit, :update, :destroy, :show] do
      member do
        post :trash
        post :untrash
        post :complete
        post :uncomplete
        patch :assign
        patch :due
      end
    resources :messages, only: [:create, :new]
    end
  end

  resources :projects do
    resources :messages
  end

end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  belongs_to :team
  has_many :todos
  has_many :events
  has_many :messages
  has_many :accesses
  has_many :members, :through => :accesses, :source => :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project_and_check_permission, only: [:edit, :update, :destroy]
  before_action :find_team, only: [:new, :create, :join, :quit]
  # before_action :member_of_project_required, only: [:show, :quit]

  def new
    @project = Project.new
  end

  def index
    @team = current_user.participated_teams.find(params[:team_id])
    @projects = @team.projects
  end

  def show
    if current_user.participated_projects.find_by(id: params[:id])
      @project = current_user.participated_projects.find(params[:id])
      @todos = @project.todos
    else
      redirect_to root_path, alert: "You are member of the project"
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Update Success!"
    else
      render :edit
    end
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.team = @team
    if @project.save
      current_user.join_project!(@project)
      redirect_to team_projects_path(@team), notice: "New Project Created!"
    else
      render :new
    end
  end

  def destroy
    @team = @project.team
    @project.destroy
    redirect_to team_projects_path(@team), alert: "Project Deleted!"
  end

  def join
    @project = Project.find(params[:id])
    if !current_user.is_member_of_project?(@project)
      current_user.join_project!(@project)
    end
    redirect_to project_path(@project)
  end

  def quit
    @project = current_user.participated_projects.find(params[:id])
    if current_user == @project.user
      flash[:alert] = "You are the creator!"
    else
      current_user.quit_project!(@project)
    end
    redirect_to team_projects_path(@team)
  end

  private

  def find_team
    @team = current_user.participated_teams.find(params[:team_id])
  end

  def find_project_and_check_permission
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def render_project_description(project)
    simple_format(project.description)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for [@team, @project] do |f| %>

<div class="form-group">
  <div class="form-group string optional">
    <%= f.input :title, input_html: {class: "form-control"} %>
    <%= f.input :description, input_html: {class: "form-control"} %>
  </div>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/projects/_project_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(project.title, project_path(project)) %></td>
  <td><%= render_project_description(project) %></td>
  <td><%= project.user.name %></td>
  <td>
    <% if current_user && current_user == project.user %>
      <%= link_to("编辑", edit_project_path(project), class: "btn btn-sm btn-default") %>
      <%= link_to("删除", project_path(project), class: "btn btn-sm btn-default", method: :delete, data: {confirm: "Are you sure?"}) %>
    <% end %>
    <% if current_user && current_user.is_member_of_project?(project) %>
      <%= link_to("退出项目", quit_team_project_path(@team, project), class: "btn btn-sm btn-danger", method: :post ) %>
    <% else %>
      <%= link_to("加入项目", join_team_project_path(@team, project), class: "btn btn-sm btn-default", method: :post ) %>
    <% end %>

  </td>
</tr>

app/views/projects/edit.html.erb
<div class="container">
  <h2>编辑项目</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/projects/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("返回团队", team_path(@team), class:"btn btn-default pull-right") %>
    <%= link_to("新建项目", new_team_project_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>项目名称</td>
        <td>项目描述</td>
        <td>项目创建人</td>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "project_item", :collection => @projects, :as => :project %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h2>新增项目</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/projects/show.html.erb
<div class="col-md-12">
  <div class="group">

    <%= link_to("返回团队", team_path(@project.team), class:"btn btn-default pull-right") %>
    <%= link_to("创建新任务", new_project_todo_path(@project), class:"btn btn-warning pull-right") %>
    <% if current_user && current_user == @project.user %>
      <%= link_to("Edit", edit_project_path(@project), class: "btn btn-primary pull-right") %>
    <% end %>
  </div>
  <h2><%= @project.title %></h2>
  <p><%= @project.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>任务名称</th>
        <th>任务描述</th>
        <th>截止日期</th>
        <th>责任人</th>
        <th>操作</th>
        <th>任务创建者</th>
        <th>项目管理员</th>
      </tr>
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= link_to(todo.title, project_todo_path(@project,todo)) %></td>
          <td><%= todo.description %></td>
          <td>
            <%= simple_form_for todo, url: due_project_todo_path(@project,todo) do |f| %>
              <%= f.input :due  %>
              <%= f.submit "Update", data: {disable_with:"Submitting..."} %>
            <% end %>
          </td>
          <td>
            <%= simple_form_for todo, url: assign_project_todo_path(@project,todo) do |f| %>
              <%= f.input :assign, :class => "form-control" %>
              <%= f.submit "Update", data: {disable_with:"Submitting..."} %>
            <% end %>
          </td>
          <td>
            <% if todo.is_trash %>
              <%= link_to("恢复任务", untrash_project_todo_path(@project,todo), class: "btn btn-default btn-sm btn-warning", :method => :post) %>
            <% else %>
              <%= link_to("删除任务", trash_project_todo_path(@project,todo) ,class: "btn btn-default btn-sm btn-danger", :method => :post) %>
            <% end %>
            <% if todo.is_completed %>
              <%= link_to("重新打开", uncomplete_project_todo_path(@project,todo) ,class: "btn btn-default btn-sm btn-warning", :method => :post) %>
            <% else %>
              <%= link_to("完成任务", complete_project_todo_path(@project,todo), class: "btn btn-default btn-sm btn-success", :method => :post) %>
            <% end %>
          </td>
          <td><h4><%= todo.user.name %></td></h4>
          <td><h4><%= @project.user.name %></td></h4>
        </tr>
      <% end %>
    </tbody>
</table>

</div>