config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'teams#index'

  resources :teams do

    member do
      post :join
      post :quit
    end

    resources :events, only: [:index]

    resources :projects do
      member do
        post :join
        post :quit
      end
    end

  end

  resources :projects do
    resources :todos, only: [:new, :create, :edit, :update, :destroy, :show] do
      member do
        post :trash
        post :untrash
        post :complete
        post :uncomplete
        patch :assign
        patch :due
      end
    resources :messages, only: [:create, :new]
    end
  end

  resources :projects do
    resources :messages
  end

end

app/models/todo.rb
class Todo < ApplicationRecord
  # after_create :event_build_when_created
  # after_update :event_build_when_updated
  validates :title, presence: true
  belongs_to :project
  belongs_to :user
  belongs_to :team
  has_many :events
  has_many :messages

  def untrash!
    self.is_trash = false
    self.save!
  end

  def trash!
    self.is_trash = true
    self.save!
  end

  def uncomplete!
    self.is_completed = false
    self.save!
  end

  def complete!
    self.is_completed = true
    self.save!
  end

  protected
  #
  # def event_build_when_created
  #   Event.build_todo(self.user, "创建了任务", self, self.project, self.team)
  # end
  #
  # def event_build_when_updated
  #   # 删除任务触发 event
  #   if self.is_trash_changed? && self.is_trash == true
  #     Event.build_todo(self.user, "删除了任务", self, self.project, self.team)
  #   # 恢复任务触发 event
  #   elsif self.is_trash_changed? && self.is_trash == false
  #     Event.build_todo(self.user, "恢复了任务", self, self.project, self.team)
  #   # 完成任务触发 event
  #   elsif self.is_completed_changed? && self.is_completed == true
  #     Event.build_todo(self.user, "完成了任务", self, self.project, self.team)
  #   # 重新打开任务触发 event
  #   elsif self.is_completed_changed? && self.is_completed == false
  #     Event.build_todo(self.user, "重新打开了任务", self, self.project, self.team)
  #   # 指派任务触发 event
  #   elsif self.assign_changed? && self.assign_was == nil
  #     Event.build_todo(self.user, "给 #{self.assign} 指派了任务", self, self.project, self.team)
  #   # 重新指派任务触发 event
  #   elsif self.assign_changed? && self.assign_was != nil
  #     Event.build_todo(self.user, "把 #{self.assign_was} 的任务指派给了 #{self.assign}", self, self.project, self.team)
  #   # 设定截止时间触发 event
  #   elsif self.due_changed? && self.due_was == nil
  #     Event.build_todo(self.user, "将任务完成时间从 没有截止日期 修改为 #{self.due}", self, self.project, self.team)
  #   # 重新设定截止时间触发 event
  #   elsif self.due_changed? && self.due_was != nil
  #     Event.build_todo(self.user, "将任务完成时间从 #{self.due_was} 修改为 #{self.due}", self, self.project, self.team)
  #   end
  # end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project
  before_action :find_todo, :only => [:show, :assign, :due, :trash, :untrash, :complete, :uncomplete]
  before_action :check_edit_permission, :only => [:edit, :update, :trash, :untrash]

  def new
    @todo = Todo.new
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to project_todo_path(@todo)
    else
      render :edit
    end
  end

  # def destroy
  #   @todo.destroy
  #   redirect_to project_path(@project)
  # end

  def show
    @messages = @todo.messages
  end

  def create
    @todo = Todo.new(todo_params)
    @team = @project.team
    @todo.project = @project
    @todo.user = current_user
    @todo.team = @team

    if @todo.save
      Event.build_todo(current_user, "创建了任务", @todo, @todo.project, @todo.team)
      redirect_to project_path(@project)
    else
      render :new
    end

  end

  def assign
    old_assgin = @todo.assign
    @todo.update(todo_params)
    new_assgin = @todo.assign
    if old_assgin != new_assgin && old_assgin == nil
      Event.build_todo(current_user, "给 #{new_assgin} 指派了任务", @todo, @todo.project, @todo.team)
    elsif old_assgin != new_assgin && old_assgin != nil
      Event.build_todo(current_user, "把 #{old_assgin} 的任务指派给了 #{new_assgin}", @todo, @todo.project, @todo.team)
    end
    redirect_to project_path(@project)
  end

  def due
    old_due = @todo.due
    @todo.update(todo_params)
    new_due = @todo.due
    if new_due != old_due && old_due == nil
      Event.build_todo(current_user, "将任务完成时间从 没有截止日期 修改为 #{new_due}", @todo, @todo.project, @todo.team)
    elsif new_due != old_due && old_due != nil
      Event.build_todo(current_user, "将任务完成时间从 #{old_due} 修改为 #{new_due}", @todo, @todo.project, @todo.team)
    end
    redirect_to project_path(@project)
  end

  def untrash
    @todo.untrash!
    Event.build_todo(current_user, "恢复了任务", @todo, @todo.project, @todo.team)
    redirect_to project_path(@project)
  end

  def trash
    @todo.trash!
    Event.build_todo(current_user, "删除了任务", @todo, @todo.project, @todo.team)
    redirect_to project_path(@project)
  end

  def complete
    @todo.complete!
    Event.build_todo(current_user, "完成了任务", @todo, @todo.project, @todo.team)
    redirect_to project_path(@project)
  end

  def uncomplete
    @todo.uncomplete!
    Event.build_todo(current_user, "重新打开了任务", @todo, @todo.project, @todo.team)
    redirect_to project_path(@project)
  end

  private

  def find_project
    @project = current_user.participated_projects.find(params[:project_id])
  end

  def check_edit_permission
    if current_user == @project.user
      @todo = Todo.find(params[:id])
    elsif current_user.todos.find_by(id: params[:id])
      @todo = current_user.todos.find(params[:id])
    else
      redirect_to project_path(@project), alert: "You can trash others' todos!"
    end
  end

  def find_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :description, :assign, :due)
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/edit.html.erb
<h2 class="text-center">编辑任务</h2>

<div class="col-md-8 col-md-offset-2">
  <%= simple_form_for [@project, @todo] do |f| %>
    <div class="form-group">
      <%= f.input :title, label: "标题", input_html: {class: "form-control"} %>
      <%= f.input :description, label: "描述", input_html: {class: "form-control"} %>
      <%= f.input :due, label: "截止日期", input_html: {class: "form-control"} %>
      <%= f.input :assign, label: "被指派者", input_html: {class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/todos/new.html.erb
<h2 class="text-center">新增任务</h2>

<div class="col-md-8 col-md-offset-2">
  <%= simple_form_for [@project, @todo] do |f| %>
    <div class="form-group">
      <%= f.input :title, label: "标题", input_html: {class: "form-control"} %>
      <%= f.input :description, label: "描述", input_html: {class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/todos/show.html.erb
<div class="col-md-12">
  <%= link_to("发表讨论", new_project_todo_message_path(@project, @todo), class:"btn btn-warning pull-right") %>
  <%= link_to("返回项目", team_project_path(@todo.team, @todo.project), class:"btn btn-default pull-right") %>
  <h2><%= @todo.title %></h2>
  <p><%= @todo.description %></p>
<hr>
  <% @messages.each do |message| %>
    <%= message.user.name %> 发表评论： <br>
    <%= message.content %>
    <hr>
  <% end %>

</div>